dd_model:
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 20

    wheel1_position_cntroller:
        type: effort_controllers/JointPositionController
        joint: base_to_wheel1
        pid: {p: 1.0, i: 1.0, d: 0.0}

    wheel2_position_cntroller:
        type: effort_controllers/JointPositionController
        joint: base_to_wheel2
        pid: {p: 1.0, i: 1.0, d: 0.0}
